### ISSUE TITLE
Prediction page crash

### ISSUE THREAD

**Issue by Gurupra5ad** [PratikGarai/GlobalWeek-Hackathon-Dreadnought#2]
After cloning the project and running it everything seems to run fine except when the prediction is initiated instead of output the page crashes telling "

ValueError at /Diseases/input/

Buffer dtype mismatch, expected 'SIZE_t' but got 'int'

"
![Screenshot from 2020-08-14 13-44-16](https://user-images.githubusercontent.com/65018081/90228699-4e354100-de34-11ea-81a0-38eb338c9280.png)

**Comment by PratikGarai** [comment]
This happened because the Random Forest model in the project was trained on a 32bit architecture and was run on a system with different architecture. I retrained the model on an x64 device and added them. It shall now work fine.
